### ISSUE TITLE
COMPILATION ERROR CL-k means

### ISSUE THREAD

**Issue by DAOUDISARA2** [TU-Berlin-DIMA/CL-kmeans#1]
I followed all the instructions to execute this code CL-kmeans, when I typed the command:
make -j`grep processor / proc / cpuinfo | wc -l`
it displays this error message:
![cl-kmeans](https://user-images.githubusercontent.com/37963683/52167787-ee2eec00-2720-11e9-9258-85d13190e152.png)

![cl-kmeans1](https://user-images.githubusercontent.com/37963683/52167779-c049a780-2720-11e9-8006-42f2887f8234.png)

note: I did the test with pc i7-3777 CPU @ 3.40ghz and GPU AMD Tahiti OpenclCL 1.1
suave with i3 with integrated graphics and the error remains the same
please someone can take me back

**Comment by LutzCle** [comment]
It might be that your compiler doesn't support the 'auto' keyword yet. Which version of Clang are you using?

**Comment by DAOUDISARA2** [comment]
I install the clang version -3.5
![clang](https://user-images.githubusercontent.com/37963683/52174817-00993c00-279a-11e9-9e8d-695e57a4db74.png)

**Comment by LutzCle** [comment]
Try upgrading to clang 3.8 or newer, I haven't tested releases that old (3.5 was released on 3 Sep 2014).

Edit: I've updated the README accordingly.

**Comment by DAOUDISARA2** [comment]
thank you very much Sir, here is another problem 
![cl-kmeansfinal](https://user-images.githubusercontent.com/37963683/52201134-e2e7d780-286a-11e9-9be7-22abed7568f8.png)

**Comment by LutzCle** [comment]
On which OpenCL platform and device are you trying to run on? And can you post a stack trace?

**Comment by DAOUDISARA2** [comment]
at the moment I work on the platform OpenCL 1.2 integrated graphics card and CPU i3 
![clinfo](https://user-images.githubusercontent.com/37963683/52210778-46ccc900-2888-11e9-9ada-366063b35201.png)

**Comment by LutzCle** [comment]
Ok, to clarify: intel_core_i7-6700K_three_stage.conf is a CPU configuration. From the screenshot, you're trying to run this on an iGPU. I have not tested this code on an Intel iGPU. So you have two options: either you modify the configuration for your iGPU, or you run this configuration on your CPU.

Concerning option 1: It would be interesting to see results from this. However, I don't have such a device to test. Thus, you'll be on your own here. If you choose this option, I would recommend you try using nvidia_gtx_1080_three_stage.conf as a starting point, and try testing different parameter combinations.

Concerning option 2: From the line "Number of devices" in your screenshot, you appear not to have installed the Intel SDK for CPUs. Go ahead and install that. Depending on your CPU, you may have to adjust the "vector_length" and "local_size" parameters using OpenCL's preferred vector length as a guideline.

Once you find a working configuration, I recommend you to run a grid search on parameters combinations to find the best results for each device.

**Comment by DAOUDISARA2** [comment]
thank you very much Sir, I will try to find a configuration that works.

**Comment by LutzCle** [comment]
You're welcome. If the issue is solved, please mark it as closed.

**Comment by DAOUDISARA2** [comment]
sorry for the delay, I have another problem here: 
![capture du 2019-02-09 15-21-40](https://user-images.githubusercontent.com/37963683/52531418-80348700-2d15-11e9-87f1-b4d4c160088e.png)

**Comment by LutzCle** [comment]
From your screenshot, your first two runs worked. You can check the measurements in the runtime_expm.csv, runtime_mnts.csv and runtime_evnt.csv files (before overwriting them in later runs, that is).

The third and fourth run couldn't allocate a device buffer with 2GB. Your device needs to have at least 3GB of global memory, as k-Means needs to space for results in addition to the input.

You can specify which OpenCL device to run on in the configuration files.

**Comment by DAOUDISARA2** [comment]
thanks, Sir  @LutzCle

**Comment by LutzCle** [comment]
@DAOUDISARA2 Please close this issue if it is resolved for you.

**Comment by DAOUDISARA2** [comment]
the problem is solved, thank you very much Sir
